language: c
script: asdf plugin-test nim https://github.com/rfrancis/asdf-nim.git 'nim -v'
before_script:
  - git clone https://github.com/asdf-vm/asdf.git asdf
  - . asdf/asdf.sh
os:
  - linux
  - osx
